theme: jekyll-theme-minimal
title: Zhi Tan
description: "Postdoctoral Fellow \n Georgia Institute of Technology \n zhi.tan at gatech.edu"
logo: /assets/img/me.jpg
author:
  name             : "Zhi Tan"
  email            : "zhi.tan at gatech.edu"