theme: jekyll-theme-minimal
title: Zhi Tan
job_title: "Postdoctoral Fellow"
school: "Georgia Institute of Technology"
email: "zhi.tan at gatech.edu"
scholar_url: "https://scholar.google.com/citations?user=vReuqbIAAAAJ&hl=en"
logo: /assets/img/me.jpg