title: Zhi Tan
job_title: "Assistant Professor"
school: "Northeastern University"
email: "zhi.tan at northeastern.edu"
scholar_url: "https://scholar.google.com/citations?user=vReuqbIAAAAJ&hl=en"
logo: /assets/img/me2.jpg
theme: jekyll-theme-minimal 